# fly.toml app configuration file generated for fly-minecraft-server on 2024-05-07T23:01:41+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-minecraft-server'
primary_region = 'jnb'

[build]
image = 'itzg/minecraft-server:latest'

[env]
AUTOSTOP_PKILL_USE_SUDO = 'TRUE'
AUTOSTOP_TIMEOUT_EST = '60'
AUTOSTOP_TIMEOUT_INIT = '60'
ENABLE_AUTOSTOP = 'TRUE'
ENABLE_WHITELIST = 'FALSE'
EULA = 'TRUE'
MEMORY = '3G'
RCON_CMDS_STARTUP = 'setworldspawn 11984 126 1548'
SEED = '1691256543523180978'
DIFFICULTY = 'normal'
PVP = 'false'
SERVER_NAME = 'UwU Minecwaft Sewvew'


[[mounts]]
source = 'minecraft_data'
destination = '/data'

[[services]]
protocol = 'tcp'
internal_port = 25565
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0


[[services.ports]]
port = 25565

[[services]]
protocol = 'tcp'
internal_port = 25575
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[services.ports]]
port = 25575

[[services.ports]]
port = 80
handlers = ['http']

[[vm]]
memory = '4gb'
cpu_kind = 'shared'
cpus = 2
