# fly.toml app configuration file generated for fly-minecraft-server on 2024-05-06T23:10:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-minecraft-server'
primary_region = 'jnb'

[build]
image = 'itzg/minecraft-server:latest'

[env]
AUTOSTOP_PKILL_USE_SUDO = 'TRUE'
AUTOSTOP_TIMEOUT_EST = '120'
AUTOSTOP_TIMEOUT_INIT = '120'
ENABLE_AUTOSTOP = 'TRUE'
EULA = 'TRUE'
MEMORY = '7G'
# WHITELIST = 'LoliHunt3r,LoliHuntr'
ENABLE_WHITELIST = 'FALSE'

[[mounts]]
source = 'minecraft_data'
destination = '/data'

[[services]]
protocol = 'tcp'
internal_port = 25565
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[services.ports]]
port = 25565

[[services.ports]]
port = 80
handlers = ['http']

[checks]
[checks.minecraft_server_tcp_check]
port = 25565
type = 'tcp'
interval = '30s'
timeout = '20s'
grace_period = '30s'

[[vm]]
memory = '8gb'
cpu_kind = 'shared'
cpus = 4
